# Generated by Django 5.2.16 on 2026-08-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkcheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='required_imports',
            field=models.TextField(blank=True, default='', help_text="Welke CharLink-koppelingen meetellen voor 'goed gekoppeld'. In het admin-paneel is dit een aankruislijst; onderwater staan hier de ids komma-gescheiden. Leeg = alles waar het lid recht op heeft.", verbose_name='Verplichte koppelingen'),
        ),
    ]
